# Generated by Django 6.0.6 on 2026-06-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='queue_type',
            field=models.CharField(choices=[('general', 'General'), ('priority', 'Priority')], default='general', max_length=20),
        ),
    ]
