# Generated by Django 6.0.6 on 2026-06-17 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_is_pregnant'),
        ('queues', '0005_queuedisruptionimpact'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduleRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_booking_date', models.DateField()),
                ('old_booking_time', models.TimeField(blank=True, null=True)),
                ('suggested_booking_date', models.DateField()),
                ('suggested_booking_time', models.TimeField(blank=True, null=True)),
                ('priority_on_reschedule', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appiled_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('disruption_impact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queues.queuedisruptionimpact')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queues.queueticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
