# Generated by Django 6.0.6 on 2026-06-18 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_date', models.DateField()),
                ('option_time', models.TextField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('available_count', models.PositiveIntegerField(default=1)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='rescheduling.reschedulerecommendation')),
            ],
            options={
                'ordering': ['option_date', 'option_time'],
                'unique_together': {('recommendation', 'option_date', 'option_time')},
            },
        ),
    ]
