# Generated by Django 6.0.6 on 2026-06-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='average_time',
            new_name='average_service_time',
        ),
    ]
