# Generated by Django 6.0.6 on 2026-06-08 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
