# Generated by Django 6.0.6 on 2026-06-10 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0002_counter_queue_type'),
        ('queues', '0002_queueticket_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueticket',
            name='assigned_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counters.counter'),
        ),
    ]
