# Generated by Django 6.0.6 on 2026-06-12 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_queuepause'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueDisruptionImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_type', models.CharField(choices=[('affected', 'Affected'), ('reschedule_risk', 'Reschedule Risk')], max_length=35)),
                ('message', models.TextField(blank=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue_pause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.queuepause')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.queueticket')),
            ],
            options={
                'unique_together': {('queue_pause', 'ticket', 'impact_type')},
            },
        ),
    ]
