import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { api, errorMessage } from "../api";
import { EmptyState, Field, FormMessage, ProtectedWorkspace, SectionHeader, StatusPill } from "../components";
import type { Branch, BranchService, Service, StaffAccount } from "../types";

type AdminTab="branches"|"services"|"capacity"|"staff";

function AdminBody(){
  const client=useQueryClient(); const [tab,setTab]=useState<AdminTab>("branches"); const [editingBranch,setEditingBranch]=useState<Branch|null>(null); const [editingService,setEditingService]=useState<Service|null>(null); const [message,setMessage]=useState(""); const [formError,setFormError]=useState("");
  const branches=useQuery({queryKey:["admin","branches"],queryFn:()=>api<Branch[]>("/api/v1/branches/admin/")});
  const services=useQuery({queryKey:["admin","services"],queryFn:()=>api<Service[]>("/api/v1/services/admin/")});
  const mappings=useQuery({queryKey:["admin","mappings"],queryFn:()=>api<BranchService[]>("/api/v1/services/admin/branch-services/")});
  const staff=useQuery({queryKey:["admin","staff"],queryFn:()=>api<StaffAccount[]>("/api/v1/accounts/admin/staff/")});
  const refresh=()=>client.invalidateQueries({queryKey:["admin"]});
  const write=useMutation({mutationFn:({path,method,body}:{path:string;method:"POST"|"PATCH";body:unknown})=>api(path,{method,body}),onSuccess:async()=>{setMessage("Changes saved.");setFormError("");setEditingBranch(null);setEditingService(null);await refresh()},onError:(err)=>setFormError(errorMessage(err,"Could not save these changes."))});
  const activate=useMutation({mutationFn:({id,is_active}:{id:number;is_active:boolean})=>api(`/api/v1/accounts/admin/staff/${id}/activation/`,{method:"PATCH",body:{is_active}}),onSuccess:refresh,onError:(err)=>setFormError(errorMessage(err))});

  function branchSubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const body={branch_code:f.get("branch_code"),name:f.get("name"),address:f.get("address"),city:f.get("city"),opening_time:f.get("opening_time"),closing_time:f.get("closing_time"),is_active:f.get("is_active")==="on"};write.mutate({path:editingBranch?`/api/v1/branches/admin/${editingBranch.id}/`:"/api/v1/branches/admin/",method:editingBranch?"PATCH":"POST",body});}
  function serviceSubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const body={service_code:f.get("service_code"),name:f.get("name"),description:f.get("description"),average_service_time:Number(f.get("average_service_time")),is_active:f.get("is_active")==="on"};write.mutate({path:editingService?`/api/v1/services/admin/${editingService.id}/`:"/api/v1/services/admin/",method:editingService?"PATCH":"POST",body});}
  function mappingSubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);write.mutate({path:"/api/v1/services/admin/branch-services/",method:"POST",body:{branch:Number(f.get("branch")),service:Number(f.get("service")),max_bookings_per_slot:Number(f.get("max_bookings_per_slot")),is_active:true}});}
  function staffSubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const role=String(f.get("role"));write.mutate({path:"/api/v1/accounts/admin/staff/",method:"POST",body:{username:f.get("username"),password:f.get("password"),first_name:f.get("first_name"),last_name:f.get("last_name"),email:f.get("email"),date_of_birth:f.get("date_of_birth"),gender:f.get("gender"),disability_status:false,role,branch:role==="system_admin"?null:Number(f.get("branch"))}});}

  return <><div className="admin-tabs" role="tablist">{(["branches","services","capacity","staff"] as AdminTab[]).map((item)=><button key={item} className={tab===item?"is-active":""} onClick={()=>{setTab(item);setMessage("");setFormError("")}}>{item==="capacity"?"Branch services":item[0].toUpperCase()+item.slice(1)}</button>)}</div><FormMessage message={message} error={formError}/>
  {tab==="branches"?<div className="admin-split"><section className="surface"><SectionHeader eyebrow="Organization" title="Branches"/><div className="admin-list">{branches.data?.map((branch)=><button key={branch.id} className={editingBranch?.id===branch.id?"admin-list-row is-selected":"admin-list-row"} onClick={()=>setEditingBranch(branch)}><div><strong>{branch.name}</strong><span>{branch.city} · {branch.branch_code}</span></div><div><span>{branch.opening_time.slice(0,5)}–{branch.closing_time.slice(0,5)}</span><StatusPill value={branch.is_active?"active":"inactive"}/></div></button>)}</div></section><section className="surface"><SectionHeader eyebrow={editingBranch?"Edit":"Create"} title={editingBranch?editingBranch.name:"New branch"} action={editingBranch?<button className="text-action" onClick={()=>setEditingBranch(null)}>New branch</button>:undefined}/><form key={editingBranch?.id||"new"} onSubmit={branchSubmit}><div className="form-grid"><Field label="Branch code"><input name="branch_code" defaultValue={editingBranch?.branch_code||""} required/></Field><Field label="Name"><input name="name" defaultValue={editingBranch?.name||""} required/></Field><Field label="City"><input name="city" defaultValue={editingBranch?.city||""} required/></Field><Field label="Address"><input name="address" defaultValue={editingBranch?.address||""} required/></Field><Field label="Opening time"><input name="opening_time" type="time" defaultValue={editingBranch?.opening_time.slice(0,5)||"08:00"} required/></Field><Field label="Closing time"><input name="closing_time" type="time" defaultValue={editingBranch?.closing_time.slice(0,5)||"17:00"} required/></Field></div><label className="check-field"><input name="is_active" type="checkbox" defaultChecked={editingBranch?.is_active??true}/><span>Active branch</span></label><button className="button button--primary">{editingBranch?"Update branch":"Create branch"}</button></form></section></div>:null}
  {tab==="services"?<div className="admin-split"><section className="surface"><SectionHeader eyebrow="Catalogue" title="Services"/><div className="admin-list">{services.data?.map((service)=><button key={service.id} className={editingService?.id===service.id?"admin-list-row is-selected":"admin-list-row"} onClick={()=>setEditingService(service)}><div><strong>{service.name}</strong><span>{service.service_code}</span></div><div><span>{service.average_service_time} min</span><StatusPill value={service.is_active?"active":"inactive"}/></div></button>)}</div></section><section className="surface"><SectionHeader eyebrow={editingService?"Edit":"Create"} title={editingService?editingService.name:"New service"} action={editingService?<button className="text-action" onClick={()=>setEditingService(null)}>New service</button>:undefined}/><form key={editingService?.id||"new"} onSubmit={serviceSubmit}><Field label="Service code"><input name="service_code" defaultValue={editingService?.service_code||""} required/></Field><Field label="Name"><input name="name" defaultValue={editingService?.name||""} required/></Field><Field label="Description"><textarea name="description" rows={4} defaultValue={editingService?.description||""}/></Field><Field label="Average service time (minutes)"><input name="average_service_time" type="number" min="1" defaultValue={editingService?.average_service_time||15} required/></Field><label className="check-field"><input name="is_active" type="checkbox" defaultChecked={editingService?.is_active??true}/><span>Active service</span></label><button className="button button--primary">{editingService?"Update service":"Create service"}</button></form></section></div>:null}
  {tab==="capacity"?<div className="admin-split"><section className="surface"><SectionHeader eyebrow="Availability" title="Branch services"/><div className="admin-list">{mappings.data?.map((mapping)=><div className="admin-list-row admin-list-row--static" key={mapping.id}><div><strong>{mapping.service_name}</strong><span>{mapping.branch_name||`Branch ${mapping.branch}`}</span></div><div><span>{mapping.max_bookings_per_slot}/slot</span><StatusPill value={mapping.is_active?"active":"inactive"}/></div></div>)}</div></section><section className="surface"><SectionHeader eyebrow="Create" title="New branch service"/><form onSubmit={mappingSubmit}><Field label="Branch"><select name="branch" required><option value="">Select branch</option>{branches.data?.filter((b)=>b.is_active).map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="Service"><select name="service" required><option value="">Select service</option>{services.data?.filter((s)=>s.is_active).map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Bookings per slot"><input name="max_bookings_per_slot" type="number" min="1" defaultValue="4" required/></Field><button className="button button--primary">Create mapping</button></form></section></div>:null}
  {tab==="staff"?<div className="admin-split"><section className="surface"><SectionHeader eyebrow="Access" title="Staff accounts"/><div className="admin-list">{staff.data?.map((person)=><div className="admin-list-row admin-list-row--static" key={person.id}><div><strong>{person.first_name||person.username} {person.last_name}</strong><span>{person.role.replaceAll("_"," ")} · {person.branch_name||"Global"}</span></div><div><StatusPill value={person.is_active?"active":"inactive"}/><button className="text-action" onClick={()=>activate.mutate({id:person.id,is_active:!person.is_active})}>{person.is_active?"Deactivate":"Activate"}</button></div></div>)}</div></section><section className="surface"><SectionHeader eyebrow="Create" title="New staff account"/><form onSubmit={staffSubmit}><div className="form-grid"><Field label="First name"><input name="first_name" required/></Field><Field label="Last name"><input name="last_name" required/></Field><Field label="Username"><input name="username" required/></Field><Field label="Email"><input name="email" type="email"/></Field><Field label="Date of birth"><input name="date_of_birth" type="date" required/></Field><Field label="Gender"><select name="gender" required><option value="other">Other</option><option value="female">Female</option><option value="male">Male</option></select></Field><Field label="Role"><select name="role" required><option value="receptionist">Receptionist</option><option value="counter_staff">Counter Staff</option><option value="branch_manager">Branch Manager</option><option value="system_admin">System Admin</option></select></Field><Field label="Branch"><select name="branch"><option value="">Global / none</option>{branches.data?.filter((b)=>b.is_active).map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="Temporary password"><input name="password" type="password" required/></Field></div><button className="button button--primary">Create staff account</button></form></section></div>:null}
  {!branches.data?.length&&tab==="branches"?<EmptyState title="No branches configured"/>:null}</>;
}

export function AdminPage(){return <ProtectedWorkspace role="system_admin" title="Administration" subtitle="Manage the operating model, not a pile of dashboard cards.">{()=> <AdminBody/>}</ProtectedWorkspace>}
