# Generated by Django 6.0.6 on 2026-06-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
    ]
